name: ghost

replicaCount: 1

image:
  repository: acr_registry/ghost
  pullPolicy: Always
  tag: v1.0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ghost.local
      paths: [/]

  tls:
    - secretName: ghost-tls-secret
      hosts:
        - ghost.local

envVars: |
  - name: privacy__useUpdateCheck
    value: "false"
  - name: APPINSIGHTS_INSTRUMENTATIONKEY
    valueFrom:
      secretKeyRef:
        name: app-insights-secret
        key: instrumentation_key
  - name: NODE_ENV
    value: "production"
  - name: url
    value: "https://ghost.local"
