{{- if .Values.podDisruptionBudget.enabled -}}
{{- $name := include "application.name" . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ $name }}
{{- end -}}